# Setup
title:               Depmix
tagline:             'Dependent mixture models (aka hidden Markov models)'
description:         'All things related to depmix'
url:                 https://depmix.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

hmmr:
  title:             hmmr
  tagline:           'Mixture and hidden Markov models with R'
  description:       'A book about defining and estimating mixture and hidden Markov models with R and an accompanying R package'
  url:               https://depmix.github.io/hmmr/
  baseurl:           ''
  permalink:         pretty
  github:
    book:
      repo:           https://github.com/depmix/hmmr-book
    package:
      repo:           https://github.com/depmix/hmmr
depmixS4:
  title:             depmixS4
  tagline:           'An R package to fit mixture and hidden Markov models'
  description:       'depmixS4 was designed for flexibility and allows you to construct and estimate a wide variety of mixture and hidden Markov models.'
  url:               https://depmix.github.io/depmixS4/
  baseurl:           ''
  permalink:         pretty
  github:
    repo:           https://github.com/depmix/depmixS4


# About/contact
author:
  maarten:
    name:              Maarten Speekenbrink
    url:               https://speekenbrink-lab.github.io/
    email:             m.speekenbrink@ucl.ac.uk
  ingmar:
    name:              Ingmar Visser
    url:               https://ingmar.org
    email:             i.visser@uva.nl

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
version:             1.1.0
github:
  repo:              https://github.com/depmix
#google_analytics_id: #UA-XXXX-Y
